baseURL = 'https://lego.js.org/'
languageCode = 'en-us'
title = 'ðŸš€ Lego Web-Components'
theme = 'docs'

enableRobotsTXT = true
enableGitInfo = false

enableInlineShortcodes = true

# Shortcodes HTML
[markup]
  [markup.highlight]
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[params]
  # github_repo_edit = "https://github.com/zkreations/docs/blob/master/demo/content"
  # date_format = "January 2, 2006"
  versions = [ "v1", "v2" ]
  # badge_url = "https://www.zkreations.com"
  # main_icon = "book-open"
  description = "Lego is a minimalist native Web-Components library for low-tech lovers with serious needs of long-term future-proof applications. This documentation describes how to install, use and hack the tool."
  main_logo = "/lego.svg"
